# Generated by Django 3.0.6 on 2020-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webDevedopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameworks', models.CharField(choices=[('Dj', 'Django'), ('NG', 'Angular'), ('RE', 'React')], default='Dj', max_length=10)),
            ],
        ),
    ]
