# Generated by Django 3.0.6 on 2020-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdevedopment',
            name='frameworks',
            field=models.CharField(choices=[('Dj', 'Django'), ('NG', 'Angular'), ('RE', 'React')], default='Dj', max_length=2),
        ),
    ]
